ServiceHost = "0.0.0.0"
ServicePort = 8080

endpoint = "localhost:9000"
access_key = "rot"
secret_key = "rootroot"
use_ssl = false
bucket = "aspirinimages"

signing_method = "HS256"
expires_in = "24h"
token = "your-jwt-secret-key"

DialTimeout = "10s"
ReadTimeout = "10s"